FROM debian:13
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv

COPY backend /backend/
RUN chmod -R 755 /backend/

WORKDIR /backend
RUN python3 -m venv .venv && \
    . .venv/bin/activate && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

EXPOSE 8000

ENTRYPOINT ["/backend/.venv/bin/python3"]
CMD ["-m", "fastapi", "run", "src/main.py"]
