FROM python:3.14-slim

COPY backend /backend/
RUN chmod -R 755 /backend/

WORKDIR /backend
RUN pip install -r requirements.txt

EXPOSE 10000

ENTRYPOINT ["python"]
CMD ["-m", "fastapi", "run", "src/main.py"]
