FROM debian:13
RUN apt-get update && apt-get install -y \
    nodejs \
    npm

COPY frontend /frontend/
RUN chmod -R 755 /frontend/

WORKDIR /frontend
RUN npm cache clean --force
RUN npm install && npm run build

EXPOSE 3000

RUN npm install -g serve

ENTRYPOINT ["npm"]
CMD ["run", "serve", "--", "-p", "3000"]
