version: "1"
projects:
- name: dts-website
  environments:
  - name: Production
    services:
    - type: web
      name: backend
      runtime: docker
      repo: https://github.com/MattCrossleyTR/dts-website
      plan: free
      region: frankfurt
      dockerContext: ./backend
      dockerfilePath: ./backend/Dockerfile
      autoDeployTrigger: commit
      buildFilter:
        paths:
        - backend/**
      envVars:
        - key: DEPLOY_ENV
          value: prod
        - key: FRONTEND_ORIGIN
          value: https://mattcrossleytr.github.io
