name: Deploy Backend

on:
  push:
    paths:
      - backend/**
      - .github/**
      - render.yml
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/tests.yml

  deploy:
    needs: test
    environment:
      name: build-backend
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        run: curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
